spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:jwt-test-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

logging:
  level:
    com.hyeonah.springbootjwt: DEBUG