INSERT INTO USER (USER_ID, USERNAME, PASSWORD, NICKNAME, ACTIVATED)
VALUES (1, 'hyeoni90', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 1);

INSERT INTO ROLE (ROLE_NAME) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE (ROLE_NAME) VALUES ('ROLE_USER');

INSERT INTO USER_ROLE (USER_ID, ROLE_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO USER_ROLE (USER_ID, ROLE_NAME) VALUES (1, 'ROLE_USER');